- hosts: localhost
  vars:
    key_name: "id_rsa"
    source_key: "./.ssh/{{key_name}}"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/{{key_name}}"
    alacritty_source_bin: "{{ lookup('env', 'HOME') }}/.cargo/bin/alacritty"
  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core
  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/dotfiles.yml
    - import_tasks: tasks/dotnet.yml
    - import_tasks: tasks/productivity-tools.yml
    - import_tasks: tasks/notifications.yml
    - import_tasks: tasks/alacritty.yml
