- hosts: localhost

  vars:
    env_home_path: "{{ lookup('env', 'HOME') }}"

    env_ssh_key_name: "id_rsa"
    env_ssh_source_key: "./.ssh/{{env_ssh_key_name}}"
    env_ssh_dest_key: "{{env_home_path}}/.ssh/{{env_ssh_key_name}}"

    env_alacritty_source_bin: "{{env_home_path}}/.cargo/bin/alacritty"
    env_fzf_source_bin: "./software/fzf/fzf"

  pre_tasks:
  - name: Update Apt
    become: true
    apt:
      force_apt_get: true
      update_cache: true
      state: present
    tags:
      - install
      - core

  tasks:
    - import_tasks: tasks/ssh.yml
    - import_tasks: tasks/core-setup.yml
    - import_tasks: tasks/dotnet.yml
    - import_tasks: tasks/productivity-tools.yml
    - import_tasks: tasks/notifications.yml
    - import_tasks: tasks/alacritty.yml
    - import_tasks: tasks/fzf.yml
    - import_tasks: tasks/zsh.yml
    - import_tasks: tasks/dotfiles.yml
#    - import_tasks: tasks/qbittorrent.yml
