- name: Install System Packages 1
  become: true
  dnf:
    name: [ "unzip", "zip", "curl", "@C Development Tools and Libraries", "@Development Tools"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2
  become: true
  dnf:
    # name: [ "picom", "curl", "htop", "lsof", "i3", "ccache", "ninja-build", "python3-pip", "dconf-editor", "nvidia-settings", "pavucontrol", "moreutils", "clangd", "ubuntu-mate-desktop" ]
    name: [ "picom", "curl", "htop", "lsof", "i3", "i3blocks", "pavucontrol", "moreutils" , "bc", "sysstat"]
  tags:
    - install
    - core

- name: Install System Packages 3
  become: true
  dnf:
    name: [ "thunar", "rofi" , "feh"]
  tags:
    - install
    - core

#- name: Install System Packages 4
#  become: true
#  dnf:
#    name: [ "autoconf", "gcc", "make", "pkg-config", "libpam0g-dev", "libcairo2-dev", "libfontconfig1-dev", "libxcb-composite0-dev", "libev-dev", "libx11-xcb-dev", "libxcb-xkb-dev", "libxcb-xinerama0-dev", "libxcb-randr0-dev", "libxcb-image0-dev", "libxcb-util0-dev", "libxcb-xrm-dev", "libxkbcommon-dev", "libxkbcommon-x11-dev", "libjpeg-dev" ]
#  tags:
#    - install
#    - core
      
# - name: Install Clang
#   become: true
#   dnf:
#     name: ["clang", "clang-11", "clang-12", "clangd", "clangd-10", "clangd-11", "clangd-12"]
#   tags:
#     - install
#     - neovim
#     - core
