- name: Ensure .ssh directory exists.
  file:
    path: "{{ env_ssh_dest_key | dirname }}"
    mode: '0700'
    state: directory
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh private key
  ansible.builtin.copy:
    src: "{{ env_ssh_source_key }}"
    dest: "{{ env_ssh_dest_key }}"
    mode: '0600'
  tags:
    - dotfiles
    - install
    - ssh

- name: Install ssh public key
  ansible.builtin.copy:
    src: "{{ env_ssh_source_key }}.pub"
    dest: "{{ env_ssh_dest_key }}.pub"
    mode: '0644'
  tags:
    - dotfiles
    - install
    - ssh

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ ansible_user_id }}"
    state: present
    key: "{{ lookup('file', '{{ env_ssh_dest_key }}.pub') }}"
