- name: Install System Packages 1
  become: true
  apt:
    name: [ "unzip", "gettext", "ninja-build", "cmake", "curl", "build-essential", "unzip"]
  tags:
    - install
    - neovim
    - core

- name: Install System Packages 2
  become: true
  apt:
    # name: [ "compton", "curl", "htop", "lsof", "i3", "ccache", "ninja-build", "python3-pip", "dconf-editor", "nvidia-settings", "pavucontrol", "moreutils", "clangd", "ubuntu-mate-desktop" ]
    name: [ "compton", "curl", "htop", "lsof", "i3", "python3-pip", "dconf-editor", "pavucontrol", "moreutils" ]
  tags:
    - install
    - core

- name: Install System Packages 3
  become: true
  apt:
    name: [ "rofi" , "feh"]
  tags:
    - install
    - core

# - name: Install Clang
#   become: true
#   apt:
#     name: ["clang", "clang-11", "clang-12", "clangd", "clangd-10", "clangd-11", "clangd-12"]
#   tags:
#     - install
#     - neovim
#     - core
