- name: Install packages
  become: true
  apt:
    name: [ "dotnet-sdk-6.0"]
  tags:
    - install
    - dotnet



    dotnet tool install --global dotnet-ef
    add path to $HOME/.dotnet/tools
    install azure data studio
    postman