- name: Install dotnet
  become: true
  apt:
    name: [ "dotnet-sdk-6.0" ]
  tags:
    - install
    - dotnet
- name: Install Entity Framework Core
  ansible.builtin.command: dotnet tool install --global dotnet-ef
  tags:
    - install
    - dotnet