- name: Install ZSH
  apt: name=zsh
  become: true
  become_user: matias
  become_method: sudo
  tags: 
    - 'dotfiles'
    - 'install'
    - 'productivity'
    - 'zsh'

- name: Change shell to zsh
  shell: chsh -s $(which zsh)
  tags: 
    - 'dotfiles'
    - 'install'
    - 'productivity'
    - 'zsh'

- name: Check that the path exists
  stat:
    path: /home/matias/.oh-my-zsh
  register: oh_my_stats
  tags: 
    - 'dotfiles'
    - 'install'
    - 'productivity'
    - 'zsh'

- name: Oh-My-Zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: oh_my_stats.stat.exists == False
  become_user: matias
  tags: 
    - 'dotfiles'
    - 'install'
    - 'productivity'
    - 'zsh'

- name: Install zsh-autocompletions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-completions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-completions"
  tags: 
    - 'dotfiles'
    - 'install'
    - 'productivity'
    - 'zsh'

- name: Install zsh-autosuggestions
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-autosuggestions.git'
    dest: "~/.oh-my-zsh/plugins/zsh-autosuggestions"
  tags: 
    - 'dotfiles'
    - 'install'
    - 'productivity'
    - 'zsh'

- name: Install zsh-syntax-highlighting
  ansible.builtin.git:
    repo: 'https://github.com/zsh-users/zsh-syntax-highlighting.git'
    dest: "~/.oh-my-zsh/plugins/zsh-syntax-highlighting"
  tags: 
    - 'dotfiles'
    - 'install'
    - 'productivity'
    - 'zsh'

